// Code generated by "stringer -type=Type"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Ping-1]
	_ = x[CreateRoomRequest-2]
	_ = x[CreateRoomResponse-3]
	_ = x[JoinRoomRequest-4]
	_ = x[IceCandidateForOwner-5]
	_ = x[IceCandidateForGuest-6]
	_ = x[IceAuthInitiate-7]
	_ = x[IceAuthResponse-8]
	_ = x[IceCandidatesEnd-9]
	_ = x[GuestDisconnected-10]
}

const _Type_name = "InvalidPingCreateRoomRequestCreateRoomResponseJoinRoomRequestIceCandidateForOwnerIceCandidateForGuestIceAuthInitiateIceAuthResponseIceCandidatesEndGuestDisconnected"

var _Type_index = [...]uint8{0, 7, 11, 28, 46, 61, 81, 101, 116, 131, 147, 164}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
